const english = {
	"language-chinese-simplified": "Chinese-Simplified",
	"language-english": 'English',
    "prologue_tutorial_start_dialogue_1": "此人面相和善，披风间却刀闪寒光。",
    "prologue_tutorial_start_dialogue_2": "我则正紧紧攥着其裤脚，与其空空如也钱袋。",
    "prologue_tutorial_start_dialogue_3": "Too late to let go, too late to quibble.",
    "prologue_tutorial_start_dialogue_4": "The stranger smiles.",
    "prologue_tutorial_start_dialogue_5": "The skin on my neck tightenes.",
    "prologue_tutorial_start_choice_1": "Struggle",
    "prologue_tutorial_start_choice_2": "Beg",
    "prologue_tutorial_start_choice_3": "Give Up",
    "prologue_tutorial_start_wait_too_long_1": "I stare at this stranger for a while, until my collar was grabbed unpatiently.",
    "prologue_tutorial_struggle_dialogue_1": "I struggle wholeheartedly!",
    "prologue_tutorial_struggle_success_dialogue_1": "我的四肢并用乱蹬乱挠很有效，对方猝不及防松开了手。",
    "prologue_tutorial_struggle_success_dialogue_2": "脸着地带来的剧痛令我头晕目眩，两眼一翻直接昏迷",
    "prologue_tutorial_struggle_fail_dialogue_1": "我四肢并用乱蹬乱挠的奋力致使对方抻长了胳膊。",
    "chenru_name": "ChenRU",
	"player_default_lname": "Zuo",
	"player_default_fname": "Men",
	"player_default_trait_name_1": "Big Sis",
	"player_default_trait_desc_1": "Chenqiao's big sis.",
	"player_default_trait_name_2": "Family",
	"player_default_trait_desc_2": "Chenru's family.",
	"player_default_intro": "Still familiar with the silhouette in mirror. How fascinating is that?"  
};